### ISSUE TITLE
Manually resolve merging in `tsg-cli` branch

### ISSUE THREAD

**Issue by cheapRoc** [joyent/triton-service-groups#28]
We should get around to merging in the `tsg-cli` branch. It'll change a bit now that we have the directory structure of #23 but we can resolve that manually. 

It looks like much of the work in the `tsg-cli` branch can be entirely moved under the new `cmd/` directory. Also, I wouldn't be against removing the `cli/` directory and moving that under `cmd/triton-sg`.

**Comment by stack72** [comment]
Migrated to a new repository as it's now a different concern
