### ISSUE TITLE
Possible race condition when removing instances from a group, or when removing a group

### ISSUE THREAD

**Issue by kwilczynski** [joyent/triton-service-groups#71]
At the moment, a slight race condition can have place when a number (usually more than one) compute instances are being removed, or when a group is being removed.

This possible race condition behaviour can manifest in a way where for a brief moment, as old instances are being removed, one or two new instances are being added and provisioned, to be immediately removed (sometimes these would linger for a while before being removed).

**Comment by cheapRoc** [comment]
Can we have steps to reproduce?

**Comment by kwilczynski** [comment]
This issue has been resolved after the Pull Request https://github.com/joyent/triton-service-groups/pull/75 was merged.
