### ISSUE TITLE
Use unique identifier (UUID) instead of a group name in the compute instance tag

### ISSUE THREAD

**Issue by kwilczynski** [joyent/triton-service-groups#72]
At the moment we use a special tag (service tag?) in order to be able to identify all the compute instances which belong to a particular group. The tag is called `tsg.name`.

Since moving to using unique identifiers (UUIDs) for the name of the group, the group name has became a non-unique entity (we do not constraint group name to be unique in a data center or globally) and more than one group can be created sharing the same group name.

This results in an unpredictable behaviour when multiple instances can be managed by more than one group, since all of them are sharing the same name through the `tsg.name` tag, potentially causing instances to be created and removed rapidly before all the Nomad maintenance jobs settle with the right number of instances being managed.

**Steps to reproduce:**

1) Create a valid template
2) Create first group (with a capacity of 5) using the template unique identifier (ID) from step (1)
3) Allow for an instance created by step (2) to be provisioned and running
4) Create second group (with capacity of 10) using the template unique identifier (ID) from step (1)
5) Allow for an instance created by step (4) to be provisioned and running

Following step (5), you will be able to observe a compute instance added and running, but the total capacity will not be 15, as initial one would expect, but the current observed capacity will be 10. This will be despite both groups still reporting their distinct capacities as both 5 and 10.

Additionally, when one removes the group created in the step (4), all of the instances matching the group name will be removed (possibly because either of the larger group capacity or because the removal job performs a sweeping deletion of every compute instance that matches a specific group name, which in this case would be all of the currently running instances), including instances created by the group that was created in the step (2). Very important to mention in such case is that the instances removed from the group created in step (2) would not be replaced/added back by the maintenance job on the Nomad side, resulting in no compute instances running at the moment, regardless of the group end-point still reporting a desired capacity of 5.

**Comment by cheapRoc** [comment]
This needs to be revisited given #75 but the point about constraining groups to have unique names could be the actionable item for this issue. We need to ensure that group name are unique for a given account which is a validation concern prior to inserts/updates.

Also, I could see us tagging instances to a particular group UUID as well. That would be hygienic than the current `tsg.name` value especially when users debug/review the created instances within their account (and use multiple TSGs).

**Comment by kwilczynski** [comment]
This issue has been resolved by not allowing multiple groups sharing the same name under the same account. It was closed in Pull Request https://github.com/joyent/triton-service-groups/pull/76.

This change also removes the need for an unique identifier (UUID) for a group to be used in lieu of a group name.
