### ISSUE TITLE
Name of the compute instances running as part of a group are using old style name convention

### ISSUE THREAD

**Issue by kwilczynski** [joyent/triton-service-groups#73]
At the moment, all the compute instances running as part of a group us old style naming convention, which is the first 8 characters of the unique identifier (UUID) of the particular instance.

We have removed an ability to set an instance name prefix (e.g., `web-`) and decided that the new name would follow a fixed pattern of `tsg-{SHORT GROUP ID}-{SHORT INSTANCE ID}`, where the `SHORT GROUP ID` denotes the first 8 characters of a group unique identifier (UUID) that the instance is part of, and where the `SHORT INSTANCE ID` denotes the first 8 characters of the unique identifier (UUID) of the particular instance (which is identical to the old style naming convention).

Having said all of that, I am not sure if this issue belong here, or in the Terraform provider (and the upcoming resource), or if we decided to go ahead with the new compute instance naming?, or rather decided against it?

**Comment by cheapRoc** [comment]
This is more so an issue for the CLI that the Nomad job uses.

**Comment by stack72** [comment]
This isn't an issue - we decided that we would **tag** the instances, not name them

I believe we can close this out

**Comment by stack72** [comment]
@kwilczynski thoughts? ☝️
