### ISSUE TITLE
Validate inputs and check for resource existence

### ISSUE THREAD

**Issue by kwilczynski** [joyent/triton-service-groups#74]
To improve and harden all the API end-points, we could consider improving validation of values in inputs to ensure that only a desired set of values are accepted, plus to potentially lower the surface area for an SQL injection attack.

Additionally, we should check if - given that the values in inputs (attributes) are correct - the dependant resource which has been references in the request actually exists as a valid entity (e.g., a template exists, etc.) or issue an error otherwise.

Validating image IDs and package IDs might be a little bit more involved, as to us these are a third-party resources, and there is very little point in caching and/or maintaining an up-to-date list on our side, but for everything else that we control we could issue a query to see whether the underlying resources are still there.

**Comment by cheapRoc** [comment]
Ref: #10

I agree that there needs to be more validation so overall I think this issue should address that.

> plus to potentially lower the surface area for an SQL injection attack.

There's a point here about lowering the surface but, in theory, we're protected by our database driver's query sanitizer. I don't believe this should be the purpose of this issue though. Identifying those holes and addressing them is another task all together.

> Validating image IDs and package IDs might be a little bit more involved

Validating image, package, and network IDs can all be done through Triton (or the compute API integration layer). For the moment this could be addressed by loading up a `triton-go` client and checking for those resources prior to inserts/updates.

**Comment by kwilczynski** [comment]
The Pull Request #76 which was merged made it impossible to add a new group without a non-existent template, therefore we have a bit of a validation there already. 👍

**Comment by stack72** [comment]
We just added validation that ImageID, Package and TemplateID are valid UUIDs - I don't believe we should validate that we are using specific Images or Packages.

We also now have constrains against both of the DB tables so I believe we are in decent shape for validation for this first pass now

Let's discuss if you disagree

**Comment by cheapRoc** [comment]
I’m fine for now, as long as we have some validation. 

The only other case I’m unsure of is how does the user get alerted that their Nomad job (group) has failed running if the image or package ID is incorrect?
