### ISSUE TITLE
Add ability to retrieve all groups using a specific template

### ISSUE THREAD

**Issue by geek** [joyent/triton-service-groups#79]
Clients are unable to safely delete a template because there isn't a way to determine if a template is being used by a group.

**Comment by kwilczynski** [comment]
Hi @geek, we recently fixed this unsafe deletion issue (see Pull Request: #88), which going forward would prevent an end-user to delete a template which is still allocated/used by at least one group.

An attempt to remove a template which is still allocated would result in a `409 Conflict` being returned.

Would this be enough to resolve this issue for you?
