### ISSUE TITLE
Add validation for UUIDs

### ISSUE THREAD

**Issue by geek** [joyent/triton-service-groups#81]
When creating a template with invalid UUIDs the template is created successfully.

```
package: "14ad9d54-d0f8-11e5--93bdb33c9583"
image_id: "342045ce-6af1-4adf--e5bfaf9de28c"
```

**Comment by stack72** [comment]
We will validate that is **is** a UUID but we will not be able to validate that it is a correct package or a correct image as this is very specific to a user requres
