### ISSUE TITLE
Creating a template succeeds for existing templates

### ISSUE THREAD

**Issue by geek** [joyent/triton-service-groups#82]
If you try to create 2 templates with the same name and different values, both will succeed and return the same template_id... this should fail since the second POST actually doesn't create any new data

request 1
```
POST /templates { template_name: 'hello', image_id: 'foo' }

{ id: '1' }
```

request 2
```
POST /templates { template_name: 'hello', image_id: 'bar' }

{ id: '1' }
```

if you `GET /templates/1` you will get `{ template_name: 'hello', image_id: 'foo' }`

**Comment by stack72** [comment]
Needs constraint on templates schema
